version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back-museo
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]